### ISSUE TITLE
Automatically add .gitignore 自动添加 .gitignore

### ISSUE THREAD

**Issue by MC-XiaoHei** [Bluemangoo/VCLight#1]
现在用VCLight-CLI创建项目时，不会自动生成带有node_modules排除的.gitignore文件，导致初次提交有可能出错。
希望自动添加或提供选项。

**Comment by Bluemangoo** [comment]
你应该把issue提到cli那里去。

**Comment by MC-XiaoHei** [comment]
可是我没找到cli...
是不是私有了

**Comment by Bluemangoo** [comment]
.gitignore不同人的习惯不太一样。

**Comment by MC-XiaoHei** [comment]
但也不会有人把node_modules提交吧（

**Comment by MC-XiaoHei** [comment]
我找到cli了

**Comment by Bluemangoo** [comment]
https://github.com/Bluemangoo/VCLight-Cli
